#!/bin/bash

server=http://54.209.251.243/artifactory
#repo=dhs-flash-snapshot-local

# Maven artifact location
#company=gov/dhs/flash/flashService
#name=dhs-flash-snapshot-local
#artifact=0.0.1-SNAPSHOT
#path=$server/$repo/$company/$name/$artifact

#path=$server/artifactory/dhs-flash-snapshot-local/gov/dhs/flash/flashService/0.0.1-SNAPSHOT


#ersion="$(xml2 < curl -s $path/maven-metadata.xml | grep /metadata/versioning/snapshotVersions/snapshotVersion/value | cut -d"=" -f2 | head -n1)"

some_path=irs-agiletech-snapshot-local/gov/irs/agiletech/account/0.0.1-SNAPSHOT 
 
mavenxmlpath=$server/$some_path/maven-metadata.xml

jarpath=$server/$some_path/account

build=`curl -s $mavenxmlpath | grep '<value>' | head -1 | sed "s/.*<value>\([^<]*\)<\/value>.*/\1/"`

url=$jarpath-$build.jar

# Download
#kill $(ps aux | grep 'java -jar' | awk '{print $2}'  | head -1)
sudo pgrep '^java*'| xargs kill -9
cd /root/app1/

rm -rf app.jar
wget -O app.jar -q -N $url



#git clone git@github.devgovcio.com:IRS/agiletech.git
#cp -r agiletech/templates/* /var/www/html
